// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/profile/screens/change_email_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:footverse/features/auth/models/user_response.dart' as _i2;
import 'package:footverse/features/profile/models/change_email_request.dart'
    as _i7;
import 'package:footverse/features/profile/models/change_password_request.dart'
    as _i6;
import 'package:footverse/features/profile/models/update_profile_request.dart'
    as _i5;
import 'package:footverse/features/profile/repositories/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserResponse_0 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  @override
  _i4.Future<_i2.UserResponse> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(this, Invocation.method(#getMe, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(this, Invocation.method(#getMe, [])),
            ),
          )
          as _i4.Future<_i2.UserResponse>);

  @override
  _i4.Future<_i2.UserResponse> updateProfile(
    _i5.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [request]),
            returnValue: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.UserResponse>);

  @override
  _i4.Future<void> changePassword(_i6.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserResponse> changeEmail(_i7.ChangeEmailRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [request]),
            returnValue: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserResponse>.value(
              _FakeUserResponse_0(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.UserResponse>);
}
