// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/cart/widgets/add_to_cart_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:footverse/features/auth/models/auth_response.dart' as _i3;
import 'package:footverse/features/auth/models/forgot_password_request.dart'
    as _i13;
import 'package:footverse/features/auth/models/login_request.dart' as _i11;
import 'package:footverse/features/auth/models/password_reset_token_response.dart'
    as _i4;
import 'package:footverse/features/auth/models/refresh_token_request.dart'
    as _i12;
import 'package:footverse/features/auth/models/register_request.dart' as _i10;
import 'package:footverse/features/auth/models/reset_password_request.dart'
    as _i15;
import 'package:footverse/features/auth/models/verify_reset_otp_request.dart'
    as _i14;
import 'package:footverse/features/auth/repositories/auth_repository.dart'
    as _i9;
import 'package:footverse/features/cart/models/add_cart_item_request.dart'
    as _i7;
import 'package:footverse/features/cart/models/cart_response.dart' as _i2;
import 'package:footverse/features/cart/models/update_cart_item_request.dart'
    as _i8;
import 'package:footverse/features/cart/repositories/cart_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartResponse_0 extends _i1.SmartFake implements _i2.CartResponse {
  _FakeCartResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordResetTokenResponse_2 extends _i1.SmartFake
    implements _i4.PasswordResetTokenResponse {
  _FakePasswordResetTokenResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i5.CartRepository {
  @override
  _i6.Future<_i2.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#getCart, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<_i2.CartResponse> addItem(_i7.AddCartItemRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [request]),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#addItem, [request])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#addItem, [request])),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<_i2.CartResponse> updateItem(
    int? cartItemId,
    _i8.UpdateCartItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [cartItemId, request]),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<_i2.CartResponse> removeItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [cartItemId]),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponse>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  @override
  _i6.Future<_i3.AuthResponse> register(_i10.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.AuthResponse> login(_i11.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.AuthResponse> refresh(_i12.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(this, Invocation.method(#refresh, [request])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<void> logout(_i12.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forgotPassword(_i13.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.PasswordResetTokenResponse> verifyResetOtp(
    _i14.VerifyResetOtpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetOtp, [request]),
            returnValue: _i6.Future<_i4.PasswordResetTokenResponse>.value(
              _FakePasswordResetTokenResponse_2(
                this,
                Invocation.method(#verifyResetOtp, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.PasswordResetTokenResponse>.value(
                  _FakePasswordResetTokenResponse_2(
                    this,
                    Invocation.method(#verifyResetOtp, [request]),
                  ),
                ),
          )
          as _i6.Future<_i4.PasswordResetTokenResponse>);

  @override
  _i6.Future<void> resetPassword(_i15.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
