// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/order/screens/checkout_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:footverse/features/address/models/address_request.dart' as _i13;
import 'package:footverse/features/address/models/address_response.dart' as _i5;
import 'package:footverse/features/address/repositories/address_repository.dart'
    as _i12;
import 'package:footverse/features/cart/models/add_cart_item_request.dart'
    as _i15;
import 'package:footverse/features/cart/models/cart_response.dart' as _i6;
import 'package:footverse/features/cart/models/update_cart_item_request.dart'
    as _i16;
import 'package:footverse/features/cart/repositories/cart_repository.dart'
    as _i14;
import 'package:footverse/features/order/models/coupon_preview_request.dart'
    as _i9;
import 'package:footverse/features/order/models/coupon_preview_response.dart'
    as _i2;
import 'package:footverse/features/order/models/order_detail_response.dart'
    as _i3;
import 'package:footverse/features/order/models/order_summary_response.dart'
    as _i11;
import 'package:footverse/features/order/models/place_order_request.dart'
    as _i10;
import 'package:footverse/features/order/repositories/order_repository.dart'
    as _i7;
import 'package:footverse/shared/models/page_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCouponPreviewResponse_0 extends _i1.SmartFake
    implements _i2.CouponPreviewResponse {
  _FakeCouponPreviewResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetailResponse_1 extends _i1.SmartFake
    implements _i3.OrderDetailResponse {
  _FakeOrderDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResponse_2<T> extends _i1.SmartFake
    implements _i4.PageResponse<T> {
  _FakePageResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressResponse_3 extends _i1.SmartFake
    implements _i5.AddressResponse {
  _FakeAddressResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponse_4 extends _i1.SmartFake implements _i6.CartResponse {
  _FakeCartResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i7.OrderRepository {
  @override
  _i8.Future<_i2.CouponPreviewResponse> previewCoupon(
    _i9.CouponPreviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#previewCoupon, [request]),
            returnValue: _i8.Future<_i2.CouponPreviewResponse>.value(
              _FakeCouponPreviewResponse_0(
                this,
                Invocation.method(#previewCoupon, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.CouponPreviewResponse>.value(
                  _FakeCouponPreviewResponse_0(
                    this,
                    Invocation.method(#previewCoupon, [request]),
                  ),
                ),
          )
          as _i8.Future<_i2.CouponPreviewResponse>);

  @override
  _i8.Future<_i3.OrderDetailResponse> placeOrder(
    _i10.PlaceOrderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeOrder, [request]),
            returnValue: _i8.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#placeOrder, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#placeOrder, [request]),
                  ),
                ),
          )
          as _i8.Future<_i3.OrderDetailResponse>);

  @override
  _i8.Future<_i4.PageResponse<_i11.OrderSummaryResponse>> getMyOrders({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [], {#page: page, #size: size}),
            returnValue:
                _i8.Future<_i4.PageResponse<_i11.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i11.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i4.PageResponse<_i11.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i11.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.PageResponse<_i11.OrderSummaryResponse>>);

  @override
  _i8.Future<_i3.OrderDetailResponse> getMyOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrder, [id]),
            returnValue: _i8.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#getMyOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#getMyOrder, [id]),
                  ),
                ),
          )
          as _i8.Future<_i3.OrderDetailResponse>);

  @override
  _i8.Future<_i3.OrderDetailResponse> cancelOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [id]),
            returnValue: _i8.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#cancelOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#cancelOrder, [id]),
                  ),
                ),
          )
          as _i8.Future<_i3.OrderDetailResponse>);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i12.AddressRepository {
  @override
  _i8.Future<List<_i5.AddressResponse>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i8.Future<List<_i5.AddressResponse>>.value(
              <_i5.AddressResponse>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i5.AddressResponse>>.value(
                  <_i5.AddressResponse>[],
                ),
          )
          as _i8.Future<List<_i5.AddressResponse>>);

  @override
  _i8.Future<_i5.AddressResponse> createAddress(_i13.AddressRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createAddress, [request]),
            returnValue: _i8.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.AddressResponse>);

  @override
  _i8.Future<_i5.AddressResponse> updateAddress(
    int? id,
    _i13.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [id, request]),
            returnValue: _i8.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
          )
          as _i8.Future<_i5.AddressResponse>);

  @override
  _i8.Future<void> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i14.CartRepository {
  @override
  _i8.Future<_i6.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#getCart, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i8.Future<_i6.CartResponse>);

  @override
  _i8.Future<_i6.CartResponse> addItem(_i15.AddCartItemRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [request]),
            returnValue: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#addItem, [request])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(this, Invocation.method(#addItem, [request])),
            ),
          )
          as _i8.Future<_i6.CartResponse>);

  @override
  _i8.Future<_i6.CartResponse> updateItem(
    int? cartItemId,
    _i16.UpdateCartItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [cartItemId, request]),
            returnValue: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
          )
          as _i8.Future<_i6.CartResponse>);

  @override
  _i8.Future<_i6.CartResponse> removeItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [cartItemId]),
            returnValue: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.CartResponse>.value(
              _FakeCartResponse_4(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
          )
          as _i8.Future<_i6.CartResponse>);
}
