// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/order/providers/order_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:footverse/features/order/models/coupon_preview_request.dart'
    as _i7;
import 'package:footverse/features/order/models/coupon_preview_response.dart'
    as _i2;
import 'package:footverse/features/order/models/order_detail_response.dart'
    as _i3;
import 'package:footverse/features/order/models/order_summary_response.dart'
    as _i9;
import 'package:footverse/features/order/models/place_order_request.dart'
    as _i8;
import 'package:footverse/features/order/repositories/order_repository.dart'
    as _i5;
import 'package:footverse/shared/models/page_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCouponPreviewResponse_0 extends _i1.SmartFake
    implements _i2.CouponPreviewResponse {
  _FakeCouponPreviewResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetailResponse_1 extends _i1.SmartFake
    implements _i3.OrderDetailResponse {
  _FakeOrderDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResponse_2<T> extends _i1.SmartFake
    implements _i4.PageResponse<T> {
  _FakePageResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i5.OrderRepository {
  @override
  _i6.Future<_i2.CouponPreviewResponse> previewCoupon(
    _i7.CouponPreviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#previewCoupon, [request]),
            returnValue: _i6.Future<_i2.CouponPreviewResponse>.value(
              _FakeCouponPreviewResponse_0(
                this,
                Invocation.method(#previewCoupon, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.CouponPreviewResponse>.value(
                  _FakeCouponPreviewResponse_0(
                    this,
                    Invocation.method(#previewCoupon, [request]),
                  ),
                ),
          )
          as _i6.Future<_i2.CouponPreviewResponse>);

  @override
  _i6.Future<_i3.OrderDetailResponse> placeOrder(
    _i8.PlaceOrderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeOrder, [request]),
            returnValue: _i6.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#placeOrder, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#placeOrder, [request]),
                  ),
                ),
          )
          as _i6.Future<_i3.OrderDetailResponse>);

  @override
  _i6.Future<_i4.PageResponse<_i9.OrderSummaryResponse>> getMyOrders({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [], {#page: page, #size: size}),
            returnValue:
                _i6.Future<_i4.PageResponse<_i9.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i9.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i4.PageResponse<_i9.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i9.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.PageResponse<_i9.OrderSummaryResponse>>);

  @override
  _i6.Future<_i3.OrderDetailResponse> getMyOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrder, [id]),
            returnValue: _i6.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#getMyOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#getMyOrder, [id]),
                  ),
                ),
          )
          as _i6.Future<_i3.OrderDetailResponse>);

  @override
  _i6.Future<_i3.OrderDetailResponse> cancelOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [id]),
            returnValue: _i6.Future<_i3.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_1(
                this,
                Invocation.method(#cancelOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_1(
                    this,
                    Invocation.method(#cancelOrder, [id]),
                  ),
                ),
          )
          as _i6.Future<_i3.OrderDetailResponse>);
}
