// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/core/router/app_router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:footverse/features/address/models/address_request.dart' as _i23;
import 'package:footverse/features/address/models/address_response.dart' as _i5;
import 'package:footverse/features/address/repositories/address_repository.dart'
    as _i22;
import 'package:footverse/features/auth/models/auth_response.dart' as _i2;
import 'package:footverse/features/auth/models/login_request.dart' as _i13;
import 'package:footverse/features/auth/models/refresh_token_request.dart'
    as _i14;
import 'package:footverse/features/auth/models/register_request.dart' as _i12;
import 'package:footverse/features/auth/repositories/auth_repository.dart'
    as _i10;
import 'package:footverse/features/cart/models/add_cart_item_request.dart'
    as _i29;
import 'package:footverse/features/cart/models/cart_response.dart' as _i8;
import 'package:footverse/features/cart/models/update_cart_item_request.dart'
    as _i30;
import 'package:footverse/features/cart/repositories/cart_repository.dart'
    as _i28;
import 'package:footverse/features/order/models/coupon_preview_request.dart'
    as _i25;
import 'package:footverse/features/order/models/coupon_preview_response.dart'
    as _i6;
import 'package:footverse/features/order/models/order_detail_response.dart'
    as _i7;
import 'package:footverse/features/order/models/order_summary_response.dart'
    as _i27;
import 'package:footverse/features/order/models/place_order_request.dart'
    as _i26;
import 'package:footverse/features/order/repositories/order_repository.dart'
    as _i24;
import 'package:footverse/features/product/models/brand_response.dart' as _i21;
import 'package:footverse/features/product/models/category_response.dart'
    as _i19;
import 'package:footverse/features/product/models/product_detail_response.dart'
    as _i4;
import 'package:footverse/features/product/models/product_summary_response.dart'
    as _i16;
import 'package:footverse/features/product/models/review_response.dart' as _i17;
import 'package:footverse/features/product/repositories/brand_repository.dart'
    as _i20;
import 'package:footverse/features/product/repositories/category_repository.dart'
    as _i18;
import 'package:footverse/features/product/repositories/product_repository.dart'
    as _i15;
import 'package:footverse/features/wishlist/models/add_wishlist_item_request.dart'
    as _i32;
import 'package:footverse/features/wishlist/models/wishlist_item_response.dart'
    as _i9;
import 'package:footverse/features/wishlist/repositories/wishlist_repository.dart'
    as _i31;
import 'package:footverse/shared/models/page_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResponse_1<T> extends _i1.SmartFake
    implements _i3.PageResponse<T> {
  _FakePageResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailResponse_2 extends _i1.SmartFake
    implements _i4.ProductDetailResponse {
  _FakeProductDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressResponse_3 extends _i1.SmartFake
    implements _i5.AddressResponse {
  _FakeAddressResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCouponPreviewResponse_4 extends _i1.SmartFake
    implements _i6.CouponPreviewResponse {
  _FakeCouponPreviewResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetailResponse_5 extends _i1.SmartFake
    implements _i7.OrderDetailResponse {
  _FakeOrderDetailResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponse_6 extends _i1.SmartFake implements _i8.CartResponse {
  _FakeCartResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWishlistItemResponse_7 extends _i1.SmartFake
    implements _i9.WishlistItemResponse {
  _FakeWishlistItemResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  @override
  _i11.Future<_i2.AuthResponse> register(_i12.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResponse>);

  @override
  _i11.Future<_i2.AuthResponse> login(_i13.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i11.Future<_i2.AuthResponse>);

  @override
  _i11.Future<_i2.AuthResponse> refresh(_i14.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
            returnValueForMissingStub: _i11.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i11.Future<_i2.AuthResponse>);

  @override
  _i11.Future<void> logout(_i14.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [request]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i15.ProductRepository {
  @override
  _i11.Future<_i3.PageResponse<_i16.ProductSummaryResponse>> searchProducts({
    String? name,
    int? brandId,
    int? categoryId,
    int? page = 0,
    int? size = 20,
    _i15.ProductSort? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #name: name,
              #brandId: brandId,
              #categoryId: categoryId,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue:
                _i11.Future<
                  _i3.PageResponse<_i16.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_1<_i16.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i3.PageResponse<_i16.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_1<_i16.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i3.PageResponse<_i16.ProductSummaryResponse>>);

  @override
  _i11.Future<_i4.ProductDetailResponse> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i11.Future<_i4.ProductDetailResponse>.value(
              _FakeProductDetailResponse_2(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i4.ProductDetailResponse>.value(
                  _FakeProductDetailResponse_2(
                    this,
                    Invocation.method(#getProduct, [id]),
                  ),
                ),
          )
          as _i11.Future<_i4.ProductDetailResponse>);

  @override
  _i11.Future<_i3.PageResponse<_i17.ReviewResponse>> getProductReviews(
    int? id, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [id],
              {#page: page, #size: size},
            ),
            returnValue:
                _i11.Future<_i3.PageResponse<_i17.ReviewResponse>>.value(
                  _FakePageResponse_1<_i17.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i3.PageResponse<_i17.ReviewResponse>>.value(
                  _FakePageResponse_1<_i17.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i11.Future<_i3.PageResponse<_i17.ReviewResponse>>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i18.CategoryRepository {
  @override
  _i11.Future<List<_i19.CategoryResponse>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i11.Future<List<_i19.CategoryResponse>>.value(
              <_i19.CategoryResponse>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i19.CategoryResponse>>.value(
                  <_i19.CategoryResponse>[],
                ),
          )
          as _i11.Future<List<_i19.CategoryResponse>>);
}

/// A class which mocks [BrandRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandRepository extends _i1.Mock implements _i20.BrandRepository {
  @override
  _i11.Future<List<_i21.BrandResponse>> getBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, []),
            returnValue: _i11.Future<List<_i21.BrandResponse>>.value(
              <_i21.BrandResponse>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i21.BrandResponse>>.value(
                  <_i21.BrandResponse>[],
                ),
          )
          as _i11.Future<List<_i21.BrandResponse>>);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i22.AddressRepository {
  @override
  _i11.Future<List<_i5.AddressResponse>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i11.Future<List<_i5.AddressResponse>>.value(
              <_i5.AddressResponse>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i5.AddressResponse>>.value(
                  <_i5.AddressResponse>[],
                ),
          )
          as _i11.Future<List<_i5.AddressResponse>>);

  @override
  _i11.Future<_i5.AddressResponse> createAddress(
    _i23.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAddress, [request]),
            returnValue: _i11.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
          )
          as _i11.Future<_i5.AddressResponse>);

  @override
  _i11.Future<_i5.AddressResponse> updateAddress(
    int? id,
    _i23.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [id, request]),
            returnValue: _i11.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.AddressResponse>.value(
              _FakeAddressResponse_3(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
          )
          as _i11.Future<_i5.AddressResponse>);

  @override
  _i11.Future<void> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i24.OrderRepository {
  @override
  _i11.Future<_i6.CouponPreviewResponse> previewCoupon(
    _i25.CouponPreviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#previewCoupon, [request]),
            returnValue: _i11.Future<_i6.CouponPreviewResponse>.value(
              _FakeCouponPreviewResponse_4(
                this,
                Invocation.method(#previewCoupon, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i6.CouponPreviewResponse>.value(
                  _FakeCouponPreviewResponse_4(
                    this,
                    Invocation.method(#previewCoupon, [request]),
                  ),
                ),
          )
          as _i11.Future<_i6.CouponPreviewResponse>);

  @override
  _i11.Future<_i7.OrderDetailResponse> placeOrder(
    _i26.PlaceOrderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeOrder, [request]),
            returnValue: _i11.Future<_i7.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_5(
                this,
                Invocation.method(#placeOrder, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i7.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_5(
                    this,
                    Invocation.method(#placeOrder, [request]),
                  ),
                ),
          )
          as _i11.Future<_i7.OrderDetailResponse>);

  @override
  _i11.Future<_i3.PageResponse<_i27.OrderSummaryResponse>> getMyOrders({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [], {#page: page, #size: size}),
            returnValue:
                _i11.Future<_i3.PageResponse<_i27.OrderSummaryResponse>>.value(
                  _FakePageResponse_1<_i27.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i3.PageResponse<_i27.OrderSummaryResponse>>.value(
                  _FakePageResponse_1<_i27.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i3.PageResponse<_i27.OrderSummaryResponse>>);

  @override
  _i11.Future<_i7.OrderDetailResponse> getMyOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrder, [id]),
            returnValue: _i11.Future<_i7.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_5(
                this,
                Invocation.method(#getMyOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i7.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_5(
                    this,
                    Invocation.method(#getMyOrder, [id]),
                  ),
                ),
          )
          as _i11.Future<_i7.OrderDetailResponse>);

  @override
  _i11.Future<_i7.OrderDetailResponse> cancelOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [id]),
            returnValue: _i11.Future<_i7.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_5(
                this,
                Invocation.method(#cancelOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i7.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_5(
                    this,
                    Invocation.method(#cancelOrder, [id]),
                  ),
                ),
          )
          as _i11.Future<_i7.OrderDetailResponse>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i28.CartRepository {
  @override
  _i11.Future<_i8.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(this, Invocation.method(#getCart, [])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i11.Future<_i8.CartResponse>);

  @override
  _i11.Future<_i8.CartResponse> addItem(_i29.AddCartItemRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [request]),
            returnValue: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(this, Invocation.method(#addItem, [request])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(this, Invocation.method(#addItem, [request])),
            ),
          )
          as _i11.Future<_i8.CartResponse>);

  @override
  _i11.Future<_i8.CartResponse> updateItem(
    int? cartItemId,
    _i30.UpdateCartItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [cartItemId, request]),
            returnValue: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
          )
          as _i11.Future<_i8.CartResponse>);

  @override
  _i11.Future<_i8.CartResponse> removeItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [cartItemId]),
            returnValue: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.CartResponse>.value(
              _FakeCartResponse_6(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
          )
          as _i11.Future<_i8.CartResponse>);
}

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i31.WishlistRepository {
  @override
  _i11.Future<List<_i9.WishlistItemResponse>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i11.Future<List<_i9.WishlistItemResponse>>.value(
              <_i9.WishlistItemResponse>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i9.WishlistItemResponse>>.value(
                  <_i9.WishlistItemResponse>[],
                ),
          )
          as _i11.Future<List<_i9.WishlistItemResponse>>);

  @override
  _i11.Future<_i9.WishlistItemResponse> addProduct(
    _i32.AddWishlistItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [request]),
            returnValue: _i11.Future<_i9.WishlistItemResponse>.value(
              _FakeWishlistItemResponse_7(
                this,
                Invocation.method(#addProduct, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i9.WishlistItemResponse>.value(
                  _FakeWishlistItemResponse_7(
                    this,
                    Invocation.method(#addProduct, [request]),
                  ),
                ),
          )
          as _i11.Future<_i9.WishlistItemResponse>);

  @override
  _i11.Future<void> removeProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeProduct, [productId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}
