// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/core/router/app_router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:footverse/features/address/models/address_request.dart' as _i29;
import 'package:footverse/features/address/models/address_response.dart' as _i6;
import 'package:footverse/features/address/repositories/address_repository.dart'
    as _i28;
import 'package:footverse/features/auth/models/auth_response.dart' as _i2;
import 'package:footverse/features/auth/models/forgot_password_request.dart'
    as _i19;
import 'package:footverse/features/auth/models/login_request.dart' as _i17;
import 'package:footverse/features/auth/models/password_reset_token_response.dart'
    as _i3;
import 'package:footverse/features/auth/models/refresh_token_request.dart'
    as _i18;
import 'package:footverse/features/auth/models/register_request.dart' as _i16;
import 'package:footverse/features/auth/models/reset_password_request.dart'
    as _i21;
import 'package:footverse/features/auth/models/user_response.dart' as _i10;
import 'package:footverse/features/auth/models/verify_reset_otp_request.dart'
    as _i20;
import 'package:footverse/features/auth/repositories/auth_repository.dart'
    as _i14;
import 'package:footverse/features/cart/models/add_cart_item_request.dart'
    as _i42;
import 'package:footverse/features/cart/models/cart_response.dart' as _i12;
import 'package:footverse/features/cart/models/update_cart_item_request.dart'
    as _i43;
import 'package:footverse/features/cart/repositories/cart_repository.dart'
    as _i41;
import 'package:footverse/features/order/models/coupon_preview_request.dart'
    as _i31;
import 'package:footverse/features/order/models/coupon_preview_response.dart'
    as _i7;
import 'package:footverse/features/order/models/order_detail_response.dart'
    as _i8;
import 'package:footverse/features/order/models/order_summary_response.dart'
    as _i33;
import 'package:footverse/features/order/models/payment_url_response.dart'
    as _i9;
import 'package:footverse/features/order/models/place_order_request.dart'
    as _i32;
import 'package:footverse/features/order/repositories/order_repository.dart'
    as _i30;
import 'package:footverse/features/product/models/brand_response.dart' as _i27;
import 'package:footverse/features/product/models/category_response.dart'
    as _i25;
import 'package:footverse/features/product/models/product_detail_response.dart'
    as _i5;
import 'package:footverse/features/product/models/product_summary_response.dart'
    as _i23;
import 'package:footverse/features/product/models/review_response.dart' as _i11;
import 'package:footverse/features/product/repositories/brand_repository.dart'
    as _i26;
import 'package:footverse/features/product/repositories/category_repository.dart'
    as _i24;
import 'package:footverse/features/product/repositories/product_repository.dart'
    as _i22;
import 'package:footverse/features/profile/models/change_email_request.dart'
    as _i37;
import 'package:footverse/features/profile/models/change_password_request.dart'
    as _i36;
import 'package:footverse/features/profile/models/update_profile_request.dart'
    as _i35;
import 'package:footverse/features/profile/repositories/profile_repository.dart'
    as _i34;
import 'package:footverse/features/review/models/create_review_request.dart'
    as _i39;
import 'package:footverse/features/review/models/update_review_request.dart'
    as _i40;
import 'package:footverse/features/review/repositories/review_repository.dart'
    as _i38;
import 'package:footverse/features/wishlist/models/add_wishlist_item_request.dart'
    as _i45;
import 'package:footverse/features/wishlist/models/wishlist_item_response.dart'
    as _i13;
import 'package:footverse/features/wishlist/repositories/wishlist_repository.dart'
    as _i44;
import 'package:footverse/shared/models/page_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordResetTokenResponse_1 extends _i1.SmartFake
    implements _i3.PasswordResetTokenResponse {
  _FakePasswordResetTokenResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResponse_2<T> extends _i1.SmartFake
    implements _i4.PageResponse<T> {
  _FakePageResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailResponse_3 extends _i1.SmartFake
    implements _i5.ProductDetailResponse {
  _FakeProductDetailResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressResponse_4 extends _i1.SmartFake
    implements _i6.AddressResponse {
  _FakeAddressResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCouponPreviewResponse_5 extends _i1.SmartFake
    implements _i7.CouponPreviewResponse {
  _FakeCouponPreviewResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetailResponse_6 extends _i1.SmartFake
    implements _i8.OrderDetailResponse {
  _FakeOrderDetailResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentUrlResponse_7 extends _i1.SmartFake
    implements _i9.PaymentUrlResponse {
  _FakePaymentUrlResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_8 extends _i1.SmartFake implements _i10.UserResponse {
  _FakeUserResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewResponse_9 extends _i1.SmartFake
    implements _i11.ReviewResponse {
  _FakeReviewResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponse_10 extends _i1.SmartFake implements _i12.CartResponse {
  _FakeCartResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWishlistItemResponse_11 extends _i1.SmartFake
    implements _i13.WishlistItemResponse {
  _FakeWishlistItemResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i14.AuthRepository {
  @override
  _i15.Future<_i2.AuthResponse> register(_i16.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i15.Future<_i2.AuthResponse>);

  @override
  _i15.Future<_i2.AuthResponse> login(_i17.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i15.Future<_i2.AuthResponse>);

  @override
  _i15.Future<_i2.AuthResponse> refresh(_i18.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
            returnValueForMissingStub: _i15.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i15.Future<_i2.AuthResponse>);

  @override
  _i15.Future<void> logout(_i18.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [request]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> forgotPassword(_i19.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i3.PasswordResetTokenResponse> verifyResetOtp(
    _i20.VerifyResetOtpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetOtp, [request]),
            returnValue: _i15.Future<_i3.PasswordResetTokenResponse>.value(
              _FakePasswordResetTokenResponse_1(
                this,
                Invocation.method(#verifyResetOtp, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i3.PasswordResetTokenResponse>.value(
                  _FakePasswordResetTokenResponse_1(
                    this,
                    Invocation.method(#verifyResetOtp, [request]),
                  ),
                ),
          )
          as _i15.Future<_i3.PasswordResetTokenResponse>);

  @override
  _i15.Future<void> resetPassword(_i21.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i22.ProductRepository {
  @override
  _i15.Future<_i4.PageResponse<_i23.ProductSummaryResponse>> searchProducts({
    String? name,
    int? brandId,
    int? categoryId,
    int? page = 0,
    int? size = 20,
    _i22.ProductSort? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #name: name,
              #brandId: brandId,
              #categoryId: categoryId,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue:
                _i15.Future<
                  _i4.PageResponse<_i23.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_2<_i23.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i15.Future<
                  _i4.PageResponse<_i23.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_2<_i23.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i4.PageResponse<_i23.ProductSummaryResponse>>);

  @override
  _i15.Future<_i5.ProductDetailResponse> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i15.Future<_i5.ProductDetailResponse>.value(
              _FakeProductDetailResponse_3(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i5.ProductDetailResponse>.value(
                  _FakeProductDetailResponse_3(
                    this,
                    Invocation.method(#getProduct, [id]),
                  ),
                ),
          )
          as _i15.Future<_i5.ProductDetailResponse>);

  @override
  _i15.Future<_i4.PageResponse<_i11.ReviewResponse>> getProductReviews(
    int? id, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [id],
              {#page: page, #size: size},
            ),
            returnValue:
                _i15.Future<_i4.PageResponse<_i11.ReviewResponse>>.value(
                  _FakePageResponse_2<_i11.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i15.Future<_i4.PageResponse<_i11.ReviewResponse>>.value(
                  _FakePageResponse_2<_i11.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i15.Future<_i4.PageResponse<_i11.ReviewResponse>>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i24.CategoryRepository {
  @override
  _i15.Future<List<_i25.CategoryResponse>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i15.Future<List<_i25.CategoryResponse>>.value(
              <_i25.CategoryResponse>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i25.CategoryResponse>>.value(
                  <_i25.CategoryResponse>[],
                ),
          )
          as _i15.Future<List<_i25.CategoryResponse>>);
}

/// A class which mocks [BrandRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandRepository extends _i1.Mock implements _i26.BrandRepository {
  @override
  _i15.Future<List<_i27.BrandResponse>> getBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, []),
            returnValue: _i15.Future<List<_i27.BrandResponse>>.value(
              <_i27.BrandResponse>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i27.BrandResponse>>.value(
                  <_i27.BrandResponse>[],
                ),
          )
          as _i15.Future<List<_i27.BrandResponse>>);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i28.AddressRepository {
  @override
  _i15.Future<List<_i6.AddressResponse>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i15.Future<List<_i6.AddressResponse>>.value(
              <_i6.AddressResponse>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i6.AddressResponse>>.value(
                  <_i6.AddressResponse>[],
                ),
          )
          as _i15.Future<List<_i6.AddressResponse>>);

  @override
  _i15.Future<_i6.AddressResponse> createAddress(
    _i29.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAddress, [request]),
            returnValue: _i15.Future<_i6.AddressResponse>.value(
              _FakeAddressResponse_4(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i6.AddressResponse>.value(
              _FakeAddressResponse_4(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
          )
          as _i15.Future<_i6.AddressResponse>);

  @override
  _i15.Future<_i6.AddressResponse> updateAddress(
    int? id,
    _i29.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [id, request]),
            returnValue: _i15.Future<_i6.AddressResponse>.value(
              _FakeAddressResponse_4(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i6.AddressResponse>.value(
              _FakeAddressResponse_4(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
          )
          as _i15.Future<_i6.AddressResponse>);

  @override
  _i15.Future<void> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i30.OrderRepository {
  @override
  _i15.Future<_i7.CouponPreviewResponse> previewCoupon(
    _i31.CouponPreviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#previewCoupon, [request]),
            returnValue: _i15.Future<_i7.CouponPreviewResponse>.value(
              _FakeCouponPreviewResponse_5(
                this,
                Invocation.method(#previewCoupon, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i7.CouponPreviewResponse>.value(
                  _FakeCouponPreviewResponse_5(
                    this,
                    Invocation.method(#previewCoupon, [request]),
                  ),
                ),
          )
          as _i15.Future<_i7.CouponPreviewResponse>);

  @override
  _i15.Future<_i8.OrderDetailResponse> placeOrder(
    _i32.PlaceOrderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeOrder, [request]),
            returnValue: _i15.Future<_i8.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_6(
                this,
                Invocation.method(#placeOrder, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i8.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_6(
                    this,
                    Invocation.method(#placeOrder, [request]),
                  ),
                ),
          )
          as _i15.Future<_i8.OrderDetailResponse>);

  @override
  _i15.Future<_i4.PageResponse<_i33.OrderSummaryResponse>> getMyOrders({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, [], {#page: page, #size: size}),
            returnValue:
                _i15.Future<_i4.PageResponse<_i33.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i33.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i15.Future<_i4.PageResponse<_i33.OrderSummaryResponse>>.value(
                  _FakePageResponse_2<_i33.OrderSummaryResponse>(
                    this,
                    Invocation.method(#getMyOrders, [], {
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i4.PageResponse<_i33.OrderSummaryResponse>>);

  @override
  _i15.Future<_i8.OrderDetailResponse> getMyOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrder, [id]),
            returnValue: _i15.Future<_i8.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_6(
                this,
                Invocation.method(#getMyOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i8.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_6(
                    this,
                    Invocation.method(#getMyOrder, [id]),
                  ),
                ),
          )
          as _i15.Future<_i8.OrderDetailResponse>);

  @override
  _i15.Future<_i8.OrderDetailResponse> cancelOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [id]),
            returnValue: _i15.Future<_i8.OrderDetailResponse>.value(
              _FakeOrderDetailResponse_6(
                this,
                Invocation.method(#cancelOrder, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i8.OrderDetailResponse>.value(
                  _FakeOrderDetailResponse_6(
                    this,
                    Invocation.method(#cancelOrder, [id]),
                  ),
                ),
          )
          as _i15.Future<_i8.OrderDetailResponse>);

  @override
  _i15.Future<_i9.PaymentUrlResponse> createPaymentUrl(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentUrl, [orderId]),
            returnValue: _i15.Future<_i9.PaymentUrlResponse>.value(
              _FakePaymentUrlResponse_7(
                this,
                Invocation.method(#createPaymentUrl, [orderId]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i9.PaymentUrlResponse>.value(
                  _FakePaymentUrlResponse_7(
                    this,
                    Invocation.method(#createPaymentUrl, [orderId]),
                  ),
                ),
          )
          as _i15.Future<_i9.PaymentUrlResponse>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i34.ProfileRepository {
  @override
  _i15.Future<_i10.UserResponse> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(this, Invocation.method(#getMe, [])),
            ),
            returnValueForMissingStub: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(this, Invocation.method(#getMe, [])),
            ),
          )
          as _i15.Future<_i10.UserResponse>);

  @override
  _i15.Future<_i10.UserResponse> updateProfile(
    _i35.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [request]),
            returnValue: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
          )
          as _i15.Future<_i10.UserResponse>);

  @override
  _i15.Future<void> changePassword(_i36.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i10.UserResponse> changeEmail(
    _i37.ChangeEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [request]),
            returnValue: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i10.UserResponse>.value(
              _FakeUserResponse_8(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
          )
          as _i15.Future<_i10.UserResponse>);
}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i38.ReviewRepository {
  @override
  _i15.Future<_i11.ReviewResponse> createReview(
    _i39.CreateReviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [request]),
            returnValue: _i15.Future<_i11.ReviewResponse>.value(
              _FakeReviewResponse_9(
                this,
                Invocation.method(#createReview, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i11.ReviewResponse>.value(
              _FakeReviewResponse_9(
                this,
                Invocation.method(#createReview, [request]),
              ),
            ),
          )
          as _i15.Future<_i11.ReviewResponse>);

  @override
  _i15.Future<_i11.ReviewResponse> updateReview(
    int? id,
    _i40.UpdateReviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [id, request]),
            returnValue: _i15.Future<_i11.ReviewResponse>.value(
              _FakeReviewResponse_9(
                this,
                Invocation.method(#updateReview, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i11.ReviewResponse>.value(
              _FakeReviewResponse_9(
                this,
                Invocation.method(#updateReview, [id, request]),
              ),
            ),
          )
          as _i15.Future<_i11.ReviewResponse>);

  @override
  _i15.Future<void> deleteReview(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i41.CartRepository {
  @override
  _i15.Future<_i12.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(this, Invocation.method(#getCart, [])),
            ),
            returnValueForMissingStub: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i15.Future<_i12.CartResponse>);

  @override
  _i15.Future<_i12.CartResponse> addItem(_i42.AddCartItemRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [request]),
            returnValue: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#addItem, [request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#addItem, [request]),
              ),
            ),
          )
          as _i15.Future<_i12.CartResponse>);

  @override
  _i15.Future<_i12.CartResponse> updateItem(
    int? cartItemId,
    _i43.UpdateCartItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [cartItemId, request]),
            returnValue: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#updateItem, [cartItemId, request]),
              ),
            ),
          )
          as _i15.Future<_i12.CartResponse>);

  @override
  _i15.Future<_i12.CartResponse> removeItem(int? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [cartItemId]),
            returnValue: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i12.CartResponse>.value(
              _FakeCartResponse_10(
                this,
                Invocation.method(#removeItem, [cartItemId]),
              ),
            ),
          )
          as _i15.Future<_i12.CartResponse>);
}

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i44.WishlistRepository {
  @override
  _i15.Future<List<_i13.WishlistItemResponse>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i15.Future<List<_i13.WishlistItemResponse>>.value(
              <_i13.WishlistItemResponse>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i13.WishlistItemResponse>>.value(
                  <_i13.WishlistItemResponse>[],
                ),
          )
          as _i15.Future<List<_i13.WishlistItemResponse>>);

  @override
  _i15.Future<_i13.WishlistItemResponse> addProduct(
    _i45.AddWishlistItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [request]),
            returnValue: _i15.Future<_i13.WishlistItemResponse>.value(
              _FakeWishlistItemResponse_11(
                this,
                Invocation.method(#addProduct, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i13.WishlistItemResponse>.value(
                  _FakeWishlistItemResponse_11(
                    this,
                    Invocation.method(#addProduct, [request]),
                  ),
                ),
          )
          as _i15.Future<_i13.WishlistItemResponse>);

  @override
  _i15.Future<void> removeProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeProduct, [productId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}
