// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/auth/screens/forgot_password_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:footverse/features/auth/models/auth_response.dart' as _i2;
import 'package:footverse/features/auth/models/forgot_password_request.dart'
    as _i9;
import 'package:footverse/features/auth/models/login_request.dart' as _i7;
import 'package:footverse/features/auth/models/password_reset_token_response.dart'
    as _i3;
import 'package:footverse/features/auth/models/refresh_token_request.dart'
    as _i8;
import 'package:footverse/features/auth/models/register_request.dart' as _i6;
import 'package:footverse/features/auth/models/reset_password_request.dart'
    as _i11;
import 'package:footverse/features/auth/models/verify_reset_otp_request.dart'
    as _i10;
import 'package:footverse/features/auth/repositories/auth_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordResetTokenResponse_1 extends _i1.SmartFake
    implements _i3.PasswordResetTokenResponse {
  _FakePasswordResetTokenResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i5.Future<_i2.AuthResponse> register(_i6.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> login(_i7.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> refresh(_i8.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> logout(_i8.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forgotPassword(_i9.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.PasswordResetTokenResponse> verifyResetOtp(
    _i10.VerifyResetOtpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetOtp, [request]),
            returnValue: _i5.Future<_i3.PasswordResetTokenResponse>.value(
              _FakePasswordResetTokenResponse_1(
                this,
                Invocation.method(#verifyResetOtp, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.PasswordResetTokenResponse>.value(
                  _FakePasswordResetTokenResponse_1(
                    this,
                    Invocation.method(#verifyResetOtp, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.PasswordResetTokenResponse>);

  @override
  _i5.Future<void> resetPassword(_i11.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
