// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/product/screens/product_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:footverse/features/auth/models/auth_response.dart' as _i5;
import 'package:footverse/features/auth/models/forgot_password_request.dart'
    as _i18;
import 'package:footverse/features/auth/models/login_request.dart' as _i16;
import 'package:footverse/features/auth/models/password_reset_token_response.dart'
    as _i6;
import 'package:footverse/features/auth/models/refresh_token_request.dart'
    as _i17;
import 'package:footverse/features/auth/models/register_request.dart' as _i15;
import 'package:footverse/features/auth/models/reset_password_request.dart'
    as _i20;
import 'package:footverse/features/auth/models/user_response.dart' as _i8;
import 'package:footverse/features/auth/models/verify_reset_otp_request.dart'
    as _i19;
import 'package:footverse/features/auth/repositories/auth_repository.dart'
    as _i14;
import 'package:footverse/features/product/models/product_detail_response.dart'
    as _i3;
import 'package:footverse/features/product/models/product_summary_response.dart'
    as _i11;
import 'package:footverse/features/product/models/review_response.dart' as _i7;
import 'package:footverse/features/product/repositories/product_repository.dart'
    as _i9;
import 'package:footverse/features/profile/models/change_email_request.dart'
    as _i27;
import 'package:footverse/features/profile/models/change_password_request.dart'
    as _i26;
import 'package:footverse/features/profile/models/update_profile_request.dart'
    as _i25;
import 'package:footverse/features/profile/repositories/profile_repository.dart'
    as _i24;
import 'package:footverse/features/review/models/create_review_request.dart'
    as _i22;
import 'package:footverse/features/review/models/update_review_request.dart'
    as _i23;
import 'package:footverse/features/review/repositories/review_repository.dart'
    as _i21;
import 'package:footverse/features/wishlist/models/add_wishlist_item_request.dart'
    as _i13;
import 'package:footverse/features/wishlist/models/wishlist_item_response.dart'
    as _i4;
import 'package:footverse/features/wishlist/repositories/wishlist_repository.dart'
    as _i12;
import 'package:footverse/shared/models/page_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailResponse_1 extends _i1.SmartFake
    implements _i3.ProductDetailResponse {
  _FakeProductDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWishlistItemResponse_2 extends _i1.SmartFake
    implements _i4.WishlistItemResponse {
  _FakeWishlistItemResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_3 extends _i1.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordResetTokenResponse_4 extends _i1.SmartFake
    implements _i6.PasswordResetTokenResponse {
  _FakePasswordResetTokenResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewResponse_5 extends _i1.SmartFake
    implements _i7.ReviewResponse {
  _FakeReviewResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_6 extends _i1.SmartFake implements _i8.UserResponse {
  _FakeUserResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i9.ProductRepository {
  @override
  _i10.Future<_i2.PageResponse<_i11.ProductSummaryResponse>> searchProducts({
    String? name,
    int? brandId,
    int? categoryId,
    int? page = 0,
    int? size = 20,
    _i9.ProductSort? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #name: name,
              #brandId: brandId,
              #categoryId: categoryId,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue:
                _i10.Future<
                  _i2.PageResponse<_i11.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_0<_i11.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i10.Future<
                  _i2.PageResponse<_i11.ProductSummaryResponse>
                >.value(
                  _FakePageResponse_0<_i11.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i2.PageResponse<_i11.ProductSummaryResponse>>);

  @override
  _i10.Future<_i3.ProductDetailResponse> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i10.Future<_i3.ProductDetailResponse>.value(
              _FakeProductDetailResponse_1(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i3.ProductDetailResponse>.value(
                  _FakeProductDetailResponse_1(
                    this,
                    Invocation.method(#getProduct, [id]),
                  ),
                ),
          )
          as _i10.Future<_i3.ProductDetailResponse>);

  @override
  _i10.Future<_i2.PageResponse<_i7.ReviewResponse>> getProductReviews(
    int? id, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [id],
              {#page: page, #size: size},
            ),
            returnValue:
                _i10.Future<_i2.PageResponse<_i7.ReviewResponse>>.value(
                  _FakePageResponse_0<_i7.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i10.Future<_i2.PageResponse<_i7.ReviewResponse>>.value(
                  _FakePageResponse_0<_i7.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i10.Future<_i2.PageResponse<_i7.ReviewResponse>>);
}

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i12.WishlistRepository {
  @override
  _i10.Future<List<_i4.WishlistItemResponse>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i10.Future<List<_i4.WishlistItemResponse>>.value(
              <_i4.WishlistItemResponse>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i4.WishlistItemResponse>>.value(
                  <_i4.WishlistItemResponse>[],
                ),
          )
          as _i10.Future<List<_i4.WishlistItemResponse>>);

  @override
  _i10.Future<_i4.WishlistItemResponse> addProduct(
    _i13.AddWishlistItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [request]),
            returnValue: _i10.Future<_i4.WishlistItemResponse>.value(
              _FakeWishlistItemResponse_2(
                this,
                Invocation.method(#addProduct, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i4.WishlistItemResponse>.value(
                  _FakeWishlistItemResponse_2(
                    this,
                    Invocation.method(#addProduct, [request]),
                  ),
                ),
          )
          as _i10.Future<_i4.WishlistItemResponse>);

  @override
  _i10.Future<void> removeProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeProduct, [productId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i14.AuthRepository {
  @override
  _i10.Future<_i5.AuthResponse> register(_i15.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i10.Future<_i5.AuthResponse>);

  @override
  _i10.Future<_i5.AuthResponse> login(_i16.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(this, Invocation.method(#login, [request])),
            ),
          )
          as _i10.Future<_i5.AuthResponse>);

  @override
  _i10.Future<_i5.AuthResponse> refresh(_i17.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(this, Invocation.method(#refresh, [request])),
            ),
            returnValueForMissingStub: _i10.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_3(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i10.Future<_i5.AuthResponse>);

  @override
  _i10.Future<void> logout(_i17.RefreshTokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [request]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> forgotPassword(_i18.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i6.PasswordResetTokenResponse> verifyResetOtp(
    _i19.VerifyResetOtpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetOtp, [request]),
            returnValue: _i10.Future<_i6.PasswordResetTokenResponse>.value(
              _FakePasswordResetTokenResponse_4(
                this,
                Invocation.method(#verifyResetOtp, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i6.PasswordResetTokenResponse>.value(
                  _FakePasswordResetTokenResponse_4(
                    this,
                    Invocation.method(#verifyResetOtp, [request]),
                  ),
                ),
          )
          as _i10.Future<_i6.PasswordResetTokenResponse>);

  @override
  _i10.Future<void> resetPassword(_i20.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i21.ReviewRepository {
  @override
  _i10.Future<_i7.ReviewResponse> createReview(
    _i22.CreateReviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [request]),
            returnValue: _i10.Future<_i7.ReviewResponse>.value(
              _FakeReviewResponse_5(
                this,
                Invocation.method(#createReview, [request]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.ReviewResponse>.value(
              _FakeReviewResponse_5(
                this,
                Invocation.method(#createReview, [request]),
              ),
            ),
          )
          as _i10.Future<_i7.ReviewResponse>);

  @override
  _i10.Future<_i7.ReviewResponse> updateReview(
    int? id,
    _i23.UpdateReviewRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [id, request]),
            returnValue: _i10.Future<_i7.ReviewResponse>.value(
              _FakeReviewResponse_5(
                this,
                Invocation.method(#updateReview, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i7.ReviewResponse>.value(
              _FakeReviewResponse_5(
                this,
                Invocation.method(#updateReview, [id, request]),
              ),
            ),
          )
          as _i10.Future<_i7.ReviewResponse>);

  @override
  _i10.Future<void> deleteReview(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i24.ProfileRepository {
  @override
  _i10.Future<_i8.UserResponse> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(this, Invocation.method(#getMe, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(this, Invocation.method(#getMe, [])),
            ),
          )
          as _i10.Future<_i8.UserResponse>);

  @override
  _i10.Future<_i8.UserResponse> updateProfile(
    _i25.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [request]),
            returnValue: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
          )
          as _i10.Future<_i8.UserResponse>);

  @override
  _i10.Future<void> changePassword(_i26.ChangePasswordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i8.UserResponse> changeEmail(_i27.ChangeEmailRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [request]),
            returnValue: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i8.UserResponse>.value(
              _FakeUserResponse_6(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
          )
          as _i10.Future<_i8.UserResponse>);
}
